apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT/TODOBACKEND
    newName: mrousu/todo-backend
    newTag: b0cc0fc6acfb785f9b09d7ec320461462e43e76a

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres.yaml
  - gateway.yaml
  - route.yaml
  - deployment.yaml
  - wiki.yaml
  - config.yaml
  - service.yaml
