apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-pong
          persistentVolumeClaim:
            claimName: pong-claim
      containers:
        - name: pingpong
          image: mrousu/pingpong:724f14ca778342c71f5aec81f24296c27fa1104e
          volumeMounts:
            - name: shared-pong
              mountPath: /usr/src/app/pongfiles
