apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- gateway.yaml
- route.yaml
- persistent-image-claim.yaml
- deployment.yaml
- config.yaml
- service.yaml
images:
- name: PROJECT/TODOAPP
  newName: mrousu/todo-app
  newTag: 34691b7a34459c59e04608d5bc845e5356e6f2f4
