apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- gateway.yaml
- route.yaml
- persistent-image-claim.yaml
- deployment.yaml
- config.yaml
- service.yaml
images:
- name: PROJECT/TODOAPP
  newName: mrousu/todo-app
  newTag: 83d11ab84811d875e1e3dc67bc9417e3c5b73b0d
