apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT/IMAGE
    newName: mrousu/todo-app:3f85c4003ddb69785640b33623cfa02ca40b25f9
resources:
  - manifests/namespace.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
  - manifests/persistent-image-claim.yaml
  - manifests/deployment.yaml
  - manifests/config.yaml
  - manifests/service.yaml
