apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/TODOAPP
  newName: mrousu/todo-app
  newTag: 9b4bc80e4e9d2b702e9d3b7b544d600c1e97f08b
resources:
- manifests/namespace.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/persistent-image-claim.yaml
- manifests/deployment.yaml
- manifests/config.yaml
- manifests/service.yaml
