apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/TODOAPP
  newName: mrousu/todo-app
  newTag: d1eb28497d416a863dfa878c73c15d4a43ca44aa
resources:
- manifests/namespace.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/persistent-image-claim.yaml
- manifests/deployment.yaml
- manifests/config.yaml
- manifests/service.yaml
