apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: mrousu/todoapp:d94522238f66ce3cc8d8b04c5206a3b1347a4814
          envFrom:
            - configMapRef:
                name: todo-configmap
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/images
