apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../base
images:
- name: PROJECT/TODOAPP
  newName: mrousu/todo-app
  newTag: bce5e726a1e9178f8a8c5bc1c284cd73f0691d6d
