apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../base
images:
- name: PROJECT/TODOBACKEND
  newName: mrousu/todo-backend
  newTag: a938192f584b1f684c2ce4e137b2166bc5c0837f
