apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: pong-claim
      containers:
        - name: todo-app
          image: mrousu/todoapp:03b6d71b1b7e4511acf7e4415a17ddc1c9acb567
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/images
