apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: pong-claim
      containers:
        - name: todo-app
          image: mrousu/todoapp:0a7c80d7a06375212feba253f031e1afcb37653f
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/images
