apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: pong-claim
      containers:
        - name: todo-app
          image: mrousu/todoapp:c225e39cbeadefc081c71904170e8040f3c422a0
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/images
