apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT/IMAGE
    newName: mrousu/todo-backend:a3011dfa6f9822feaf945f69bc07ed62a3376244

resources:
  - manifests/namespace.yaml
  - manifests/postgres-secret.yaml
  - manifests/postgres.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
  - manifests/deployment.yaml
  - manifests/config.yaml
  - manifests/service.yaml
