apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT/IMAGE
    newName: mrousu/todo-backend:3.5

resources:
  - manifests/namespace.yaml
  - manifests/postgres-secret.yaml
  #- manifests/postgres.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
  - manifests/deployment.yaml
  - manifests/config.yaml
  - manifests/service.yaml
